export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const OTHER_ON = "OTHER_ON";
export const OTHER_OFF = "OTHER_OFF";

export const NOTIFICATION_NEW = "NOTIFICATION_NEW";
export const NOTIFICATION_CLOSE = "NOTIFICATION_CLOSE";

export const UI_OPEN_SIDEBAR = "UI_OPEN_SIDEBAR";
export const UI_CLOSE_SIDEBAR = "UI_CLOSE_SIDEBAR";
export const UI_TOGGLE_SIDEBAR = "UI_TOGGLE_SIDEBAR";
export const UI_IS_ADDING_LOCATION = "UI_IS_ADDING_LOCATION";
export const UI_SELECTED_MARKER = "UI_SELECTED_MARKER";
export const UI_OPEN_BOTTOMBAR = "UI_OPEN_BOTTOMBAR";
export const UI_CLOSE_BOTTOMBAR = "UI_CLOSE_BOTTOMBAR";
export const UI_TOGGLE_BOTTOMBAR = "UI_TOGGLE_BOTTOMBAR";

export const MAP_SET_MARKER = "MAP_SET_MARKER";
export const MAP_RESET_MARKER = "MAP_RESET_MARKER";
