// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_appsync_graphqlEndpoint": "https://r42x77vyhzak5apj5whq2e6j3e.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-n422ytmqxjatrhxpsbyk3smzki",
    "aws_cognito_identity_pool_id": "us-west-2:3d4ee65c-646d-4811-8c49-b3e717214c20",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_Fa5ONYgZO",
    "aws_user_pools_web_client_id": "3a8aktrabl7l6pg8nb13sn7cvc",
    "aws_content_delivery_bucket": "feedback-map-react-20190327134610-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "http://feedback-map-react-20190327134610-hostingbucket-dev.s3-website-us-west-2.amazonaws.com"
};


export default awsmobile;
